[build-system]
requires = ["hatchling>=1.4", "jupyter_client>=8"]
build-backend = "hatchling.build"

[project]
name = "async_kernel"

dynamic = ["version"]
authors = [{name = "IPython Development Team", email = "ipython-dev@python.org"}]
license = {file = "LICENSE"}
readme = "README.md"
description = "An Asynchronous Python kernel for Jupyter using anyio with asyncio (normal or eager task factory) or trio event loops."
keywords = ["Interactive", "Interpreter", "Shell", "Web", "Jupyter"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.4",
    "comm>=0.2.2",
    "traitlets>=5.14.3",
    "jupyter_client>=8.6.3",
    "jupyter_core>=5.8.1",
    "pyzmq>=26.0",
    "anyio>=4.8.0,<5.0.0",
    "typing_extensions",
    "sniffio",
    "matplotlib-inline>=0.1"
]

[project.urls]
# Homepage = ""
# Documentation = ""
# Source = ""
# Tracker = ""

[project.scripts]
async_kernel = "async_kernel.__main__:main"

[project.optional-dependencies]
docs = [
  "sphinx",
  "myst_parser",
  "pydata_sphinx_theme",
  "sphinxcontrib_github_alt",
  "sphinxcontrib-spelling",
  "sphinx-autodoc-typehints",
  "intersphinx_registry",
  "trio"
]
test = [
    "debugpy",
    "pre-commit",
    "pytest-cov",
    "pytest-timeout",
    "pytest-mock",
    "pytest>=8.4,<9",
    "matplotlib",
    "trio",
]
cov = [
  "coverage[toml]",
  "pytest-cov",
  "matplotlib",
  "trio",
]

[tool.hatch.version]
path = "src/async_kernel/_version.py"

# Used to call hatch_build.py
[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.wheel.shared-data]
"data_kernelspec" = "share/jupyter/kernels"


[tool.hatch.envs.docs]
features = ["docs"]
[tool.hatch.envs.docs.scripts]
build = "make -C docs html SPHINXOPTS='-W'"
api = "sphinx-apidoc -o docs/api -f"

[tool.hatch.envs.test]
features = ["test"]
[tool.hatch.envs.test.scripts]
list = "python -m pip freeze"
test = "python -m pytest -vv {args}"
nowarn = "test -W default {args}"

[tool.hatch.envs.cov]
features = ["test", "cov"]
[tool.hatch.envs.cov.scripts]
test = "python -m pytest -vv --cov async_kernel --cov-branch --cov-report term-missing:skip-covered {args}"
nowarn = "test -W default {args}"

[[tool.hatch.envs.cov.matrix]]
qt = ["qt5", "qt6"]


[tool.hatch.envs.typing]
dependencies = ["pre-commit"]
detached = true

[tool.hatch.envs.lint]
dependencies = ["pre-commit"]
detached = true
[tool.hatch.envs.lint.scripts]
build = [
  "pre-commit run --all-files ruff",
  "pre-commit run --all-files ruff-format"
]


[tool.pytest.ini_options]
minversion = "6.0"
xfail_strict = true
log_cli_level =  "INFO"
addopts = [
  "-raXs", "--durations=10", "--color=yes", "--doctest-modules",
   "--showlocals", "--strict-markers", "--strict-config",
  "-s",
]
testpaths = ["tests"]

filterwarnings= []

[tool.coverage.report]
exclude_lines = [
  "def __repr__",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "class .*\bProtocol\\):",
  "@(abc\\.)?abstractmethod",
  "except .*",
  "def excepthook.*" # Pytest overrides excepthook
]

[tool.coverage.run]
parallel = true
relative_files = true
source = ["async_kernel"]
omit = ["tests/*", "hatch_build.py"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
  "B",        # flake8-bugbear
  "I",        # isort
  "F",        # Pyflakes
  "ARG",      # flake8-unused-arguments
  "C4",       # flake8-comprehensions
  "EM",       # flake8-errmsg
  "ICN",      # flake8-import-conventions
  "G",        # flake8-logging-format
  "PERF",     # Perflint
  "PGH",      # pygrep-hooks
  "PIE",      # flake8-pie
  "PL",       # pylint
  "PLR",      # Refactor
  "PT",       # flake8-pytest-style
  "PTH",      # flake8-use-pathlib
  "RET",      # flake8-return
  "RUF",      # Ruff-specific
  "SIM",      # flake8-simplify
  "T20",      # flake8-print
  "TRY",      # tryceratops
  "FURB",     # Refurb
  "UP",       # pyupgrade
  "YTT",      # flake8-2020
  "EXE",      # flake8-executable
  "NPY",      # NumPy specific rules
  "PD",       # pandas-vet
  "PYI",      # flake8-pyi
  "TC",       # flake8-type-checking
]
ignore = [
  "PLR",    # Design related pylint codes
  "B027", # Allow non-abstract empty methods in abstract base classes
  "T201", # `print` found
  "SIM105", # Use `contextlib.suppress(ValueError)` instead of try-except-pass
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
  "ARG001", # Unused function argument
  "ARG002",  # Unused method argument
  "PTH123", # `open()` should be replaced by `Path.open()`
  "UP031", # Use format specifiers instead of percent format
  "PT023", # Use `@pytest.mark.skip` over `@pytest.mark.skip()`
]

[tool.ruff.format]
docstring-code-format = true

[tool.interrogate]
ignore-init-module=true
ignore-private=true
ignore-semiprivate=true
ignore-property-decorators=true
ignore-nested-functions=true
ignore-nested-classes=true
fail-under=95
exclude = ["docs", "tests"]

[tool.check-wheel-contents]
toplevel = ["async_kernel/"]
ignore = ["W002"]

[tool.repo-review]
ignore = ["PY007", "PP308", "GH102", "MY101"]

[tool.hatch.metadata]
allow-direct-references = true
