name: Async-kernel tests

on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.6"
          python-version: ${{ matrix.python-version }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the project
        run: uv sync --locked --dev

      - name: Run the tests
        timeout-minutes: 5
        run: uv run pytest -v

      - name: Ruff
        uses: astral-sh/ruff-action@v3

      - name: Type checking
        run: uv run basedpyright

      - name: Build
        run: uv build

      - name: Distribution
        uses: actions/upload-artifact@v4
        with:
          name: "dist ${{ github.job }}-${{ strategy.job-index }}"
          path: dist/*

      - name: Coverage
        if: ${{ ( matrix.python-version >= '3.12' ) && ( matrix.os  ==  'ubuntu-latest' ) }}
        run: uv run pytest --cov  --cov-fail-under 99
