name: Enforce PR label and pre-commit

concurrency:
  group: label-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: enforce-triage-label
        uses: jupyterlab/maintainer-tools/.github/actions/enforce-label@v1

      - name: pre-commit
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
